
export const ActionTypes = {
  SET_PRODUCTS: 'SET_PRODUCTS',
  REMOVE_SET_PRODUCTS: 'REMOVE_SET_PRODUCTS',
  SELECTED_PRODUCT: 'SELECTED_PRODUCT',
  REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT',
  CART_PRODUCTS: 'CART_PRODUCTS',
  REMOVE_CART_PRODUCT: 'REMOVE_CART_PRODUCT',
  DELETE_CART_PRODUCT: 'DELETE_CART_PRODUCT',
  LIKED_PRODUCTS: 'LIKED_PRODUCTS',
  REMOVE_LIKED_PRODUCTS: 'REMOVE_LIKED_PRODUCTS',
  CHECKOUT_PRODUCTS: 'CHECKOUT_PRODUCTS',
  REMOVE_CHECKOUT_PRODUCT: 'REMOVE_CHECKOUT_PRODUCT',
  SET_CHECKED_STATUS: 'SET_CHECKED_STATUS',
  UNSET_CHECKED_STATUS: 'UNSET_CHECKED_STATUS',
}

export default ActionTypes